// src/lib/components/Footer.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
</script>

<footer class="mx-auto p-4">
	<ul class="flex gap-4 text-center text-xs">
		<li>
			<a class="text-foreground-muted hover:text-link" href="https://start.omfj.no"
				>[start.omfj.no]</a
			>
		</li>
		<li>
			<a class="text-foreground-muted hover:text-link" href={resolve('/habits')}>[Habit Tracker]</a>
		</li>
		<li>
			<a class="text-foreground-muted hover:text-link" href={resolve('/omdb')}>[OMDb]</a>
		</li>
	</ul>
</footer>

// apps/web/src/components/footer.tsx
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="border-t py-5 text-center">
      <p className="text-sm text-gray-500">
        © {new Date().getFullYear()}{" "}
        <Link className="hover:underline" href="https://github.com/omfj/omfj.no">
          Made with ❤️ by omfj
        </Link>
      </p>
    </footer>
  );
}
